[package]
name = "csvcut"
version = "0.1.1"
edition = "2021"
authors = ["berquerant"]
readme = "README.md"
repository = "https://github.com/berquerant/csvcut"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
nom = "8"
csv = "1.3"
serde_json = "1.0"