[package]
name = "csvcut"
version = "0.1.0"
edition = "2021"
authors = ["berquerant"]
readme = "README.md"
repository = "https://github.com/berquerant/csvcut"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
nom = "7"
csv = "1.1"
serde_json = "1.0"